src/Entity/Training.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrainingRepository")
 */
class Training
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * ENTITE PROPRIETAIRE DE LA RELATION
     * @ORM\ManyToMany(targetEntity="App\Entity\Module", inversedBy="trainings",cascade={"persist"})
     */
    private $modules;

    public function __construct()
    {
        $this->modules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|module[]
     */
    public function getModules(): Collection
    {
        return $this->modules;
    }

    public function addModule(module $module): self
    {
        if (!$this->modules->contains($module)) {
            $this->modules[] = $module;
        }

        return $this;
    }

    public function removeModule(module $module): self
    {
        if ($this->modules->contains($module)) {
            $this->modules->removeElement($module);
        }

        return $this;
    }
}

src/Form/TrainingType.php
<?php

namespace App\Form;

use App\Entity\Training;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TrainingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class,[
                'label' => 'Name'
            ])
            ->add('slug',TextType::class,[
                'label' => 'Slug'
            ])
            ->add('Description',TextareaType::class,[
                'label' => 'Description'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Training::class,
        ]);
    }
}

src/Controller/ex2/ModuleController.php
<?php

namespace App\Controller\ex2;

use App\Entity\Module;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ModuleController extends AbstractController
{
    /**
     * @Route("/modules", name="modules")
     */
    public function modules()
    {
        //Liste des modules
        $modules= $this->getDoctrine()->getRepository(Module::class)->findAll();

        return $this->render('ex2/module/modules.html.twig', [
            'modules' => $modules
        ]);
    }

    /**
     * Ajouter un module à une formation
     * @Route("/addModule", name="add_module")
     */
    public function add()
    {        
        
        return $this->render('ex2/module/addModule.html.twig', [
           
        ]);
    }

    /**
     * éditer un module
     * @Route("/editModule/{id}",name="edit_module")
     */
    public function edit($id)
    {

        //redirection
        return $this->redirectToRoute('modules');
    }

    /**
     * supprimer un module
     * @Route("/deleteModule/{id}",name="delete_module")
     */
    public function delete($id)
    {

        //redirection
        return $this->redirectToRoute('modules');
    }

    /**
     * consulter un module
     * @Route("/module/{id}",name="view_module")
     */
    public function view($id)
    {

        $module = $this->getDoctrine()->getRepository(Module::class)->find($id);

        return $this->render('ex2/module/viewModule.html.twig', [
            'module' => $module 
        ]);
    }

   /**
     * consulter la liste des formations disposant du module
     * @Route("/module/{id}/trainings",name="view_module_trainings")
     */
    public function viewModuleTrainings($id)
    {

        $module = $this->getDoctrine()->getRepository(Module::class)->find($id);

        return $this->render('ex2/module/viewModuleTrainings.html.twig', [
            'module' => $module 
        ]);
    }
}

src/Controller/ex2/TrainingController.php
<?php

namespace App\Controller\ex2;

use App\Entity\Training;
use App\Entity\Module;
use App\Form\TrainingType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TrainingController extends AbstractController
{

    /*public function bdd(){


    }*/

    /**
     * Home
     * @Route("/home", name="home")
     */
    public function home()
    {

        ////////////////////////////////////////////////////////////////
        //création des formations avec modules en utilisant addModule()
 /*       $em = $this->get('doctrine')->getManager();

        //Création des formations      
        //FORMATION 1
        $formation1 = new Training;
        $formation1->setName('BackOffice Web Developper');
        $formation1->setSlug('backoffice-webdevelopper');
        $formation1->setDescription('Lorem1');
        $em->persist($formation1);

        //FORMATION 2
        $formation2 = new Training;
        $formation2->setName('Front-end Web Developper');
        $formation2->setSlug('Front-end-WebDevelopper');
        $formation2->setDescription('Lorem2');
        $em->persist($formation2);

        //FORMATION 3
        $formation3 = new Training;
        $formation3->setName('Web Designer');
        $formation3->setSlug('Web-Designer');
        $formation3->setDescription('Lorem3');
        $em->persist($formation3);
        
        //Création des modules
        $module1 = new Module();
        $module1->setName('HTML CSS');
        $em->persist($module1);

        $module2 = new Module();
        $module2->setName('PHP');
        $em->persist($module2);
 
        $module3 = new Module();
        $module3->setName('MYSQL');
        $em->persist($module3);

        $module4 = new Module();
        $module4->setName('HTML');
        $em->persist($module4);

        $module5 = new Module();
        $module5->setName('JavaScript');
        $em->persist($module5);

        $module6 = new Module();
        $module6->setName('Bootstrap');
        $em->persist($module6);

        $module7 = new Module();
        $module7->setName('Photoshop');
        $em->persist($module7);

        $module8 = new Module();
        $module8->setName('Illustrator');
        $em->persist($module8);

        //Rattachement des modules par formation
        //1
        $formation1->addModule($module1);
        $formation1->addModule($module2);
        $formation1->addModule($module3);
        //2
        $formation2->addModule($module1);
        $formation2->addModule($module5);
        $formation2->addModule($module6);
        //3
        $formation3->addModule($module1);
        $formation3->addModule($module7);
        $formation3->addModule($module8);
        $formation3->addModule($module6);
        
        $em->flush();*/
        ////////////////////////////////////////////////////////////////

        //Liste des formations
        $trainings= $this->getDoctrine()->getRepository(Training::class)->findAll();

        return $this->render('ex2/home.html.twig', [
            'trainings' => $trainings
        ]);
    }

    /**
     * Liste des formations
     * @Route("/trainings", name="trainings")
     */
    public function trainings()
    {

        $trainings = $this->getDoctrine()->getRepository(Training::class)->findAll();

        return $this->render('ex2/training/trainings.html.twig', [
            'trainings' => $trainings 
        ]);
    }

    /**
     * Création des formations
     * @Route("/add", name="add")
     */
    public function add(Request $request)
    {
        $training = new Training();

        //Création du formulaire
        $form = $this->createForm(TrainingType::class,$training);

        //Traitement du formulaire
        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form->isValid()){
                
                $em = $this->get('doctrine')->getManager();

                $em->persist($training);
                $em->flush();

                //message flash
                $this->addFlash('notice','The training has been created !');
               
                //redirection
                return $this->redirectToRoute('home');
            }
        } 

        return $this->render('ex2/training/add.html.twig', [
            'form' => $form->createView() 
        ]);
    }

    /**
     * Modification des formations
     * @Route("/edit/{slug}", name="edit")
     */
    public function edit(Request $request,$slug)
    {
        $data = $this->getDoctrine()->getRepository(Training::class)->findBySlug($slug);

        $training = $data[0];

        //Création du formulaire
        $form = $this->createForm(TrainingType::class,$training);

        //Traitement du formulaire
        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form->isValid()){
                
                $em = $this->get('doctrine')->getManager();

                $em->persist($training);
                $em->flush();

                //message flash
                $this->addFlash('notice','The training has been updated !');
               
                //redirection
                return $this->redirectToRoute('trainings');
            }
        } 

        return $this->render('ex2/training/add.html.twig', [
            'form' => $form->createView() 
        ]);
    }

    /**
     * Suppression d'une formation
     * @Route("/delete/{slug}", name="delete")
     */
    public function delete(Request $request,$slug)
    {

        $this->addFlash('notice','The training has been deleted !');
            
        return $this->redirectToRoute('home');
    }

    /**
     * Ajout d'un module à une formation
     * @Route("/addModule/{slug}", name="add_module_training")
     */
    public function addModuleToTraining()
    {        
        
        return $this->render('ex2/training/addModuleToTraining.html.twig', [
           
    ]);

    }

    /**
     * consulter une formation
     * @Route("/training/{slug}",name="view")
     */
    public function view($slug)
    {

        $training = $this->getDoctrine()->getRepository(Training::class)->findBySlug($slug);

        return $this->render('ex2/training/view.html.twig', [
            'training' => $training 
        ]);
    }
}

templates/ex2/training/add.html.twig
{% extends 'ex2/layout.html.twig' %}

{% block title %}Training Form{% endblock %}

{% block main %}

    <h2>Training Form</h2>
    
    {{ form_start(form) }}
    {{form_widget(form) }}
    <button class="btn btn-default" type="submit">Save</button>
    <button class="btn btn-default"><a href="{{ path('trainings') }}">Cancel</a></button>
    {{ form_end(form) }}

{% endblock %}

templates/ex2/training/addModuleToTraining.html.twig
Ajout d'un module

templates/ex2/training/trainings.html.twig
{% extends 'ex2/layout.html.twig' %}

{% block title %}Trainings List{% endblock %}

{% block main %}

<div class="row">
    <div class="col-xs-12">

        <h2>Trainings list</h2>
        
        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Description</th>
                    <th>Modules de la formation</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for training in trainings %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td><a href="{{ path('view',{slug:training.slug}) }}">{{ training.name }}</a></td>
                    <td>{{ training.slug }}</td>
                    <td>{{ training.description }}</td>
                    <td>
                        {% for module in training.modules %}
                            <li><a href="{{ path('view_module',{id:module.id}) }}">{{ module.name }}</a></li>
                        {% endfor %}
                    </td>
                    <td>
                        <button class="btn btn-default"><a href="{{ path('edit',{slug:training.slug}) }}">Modifier</a></button>
                        <button class="btn btn-default"><a href="{{ path('delete',{slug:training.slug}) }}">Supprimer</a></button>
                        <button class="btn btn-default"><a href="{{ path('add_module',{slug:training.slug}) }}">Ajouter un module à la formation</a></button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/ex2/training/view.html.twig
{% extends 'ex2/layout.html.twig' %}

{% block title %}Training Detail{% endblock %}

{% block main %}

<div class="row">
    <div class="col-xs-12">
        <button><a href="{{ path('edit',{slug:training[0].slug})}}">Update</a></button>
        <h3>Modules list for this training :</h3>
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <td>{{ training[0].name }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ training[0].slug }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ training[0].description }}</td>
            </tr>
        </table>

        <h3>Modules list for this training :</h3>
        <div class="card">
            <ul>
                {% for module in training[0].modules %}
                    <li>{{ module.name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}